apiVersion: v1
kind: ConfigMap
metadata:
    name: cm-private-api
    namespace: public
data:
    PRIVATE_API: ENC[AES256_GCM,data:O/HoD4HtLio3/0RZ3Uj2/appOybuvU0C3uL99Y28IWA4NL6y7xHXK0OK2vcgujBTwu6GNAPte9nG6YJppA==,iv:nld/sCL9t3nOTPIQ7htY1JsbpDiEyaOeibS2e5L33kA=,tag:4KfQqh5yDirXNGuMzv4Pvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-13T07:20:50Z"
    mac: ENC[AES256_GCM,data:nf/0nstm7pDZ9lZjFidS1t13tK8oczM7iofDpV0e/T7T2VbIOI93EwF+/k85BxR1AW1rZTrej2NDerxmaA4Mlh7o2K+I4KHP18pDl81YPRnILcwGql15vFoZrN2FhowelsM0qPchnU9y6TDZkYy6XMXwXPi4WaxGtJ2/6BNv+SE=,iv:9yY0azPGZ7Rg/clhMhAv6ttsu5vVr3za958ZpuY5NGY=,tag:oNzq/f4KCgMheYpQxd/fCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: cm-webpage-config
    namespace: public
data:
    CONFIG_JS: ENC[AES256_GCM,data:LeAt/4/ChMDoQNad1B/b27XzLJ0omYXNSCfaZo8gkejorXhkztpqYNhRgrc4ih9B+pLwJ47tTiBRn/OEmADezH0ya2DvHx95jGopd727IFpwcWE7I/zKh+Xnb1eS1RNYUlz1KglaItqUT8g6YkdpBI6/TJDaS56TOSg/X3yLi3XnTRktoRA=,iv:j09SBTw8/2VyFxAthrQo28noAgPvbgM6/exyZV65dWE=,tag:yugwJ2UnkGWQ66tmi1dafw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-13T07:20:50Z"
    mac: ENC[AES256_GCM,data:nf/0nstm7pDZ9lZjFidS1t13tK8oczM7iofDpV0e/T7T2VbIOI93EwF+/k85BxR1AW1rZTrej2NDerxmaA4Mlh7o2K+I4KHP18pDl81YPRnILcwGql15vFoZrN2FhowelsM0qPchnU9y6TDZkYy6XMXwXPi4WaxGtJ2/6BNv+SE=,iv:9yY0azPGZ7Rg/clhMhAv6ttsu5vVr3za958ZpuY5NGY=,tag:oNzq/f4KCgMheYpQxd/fCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
