apiVersion: v1
kind: ConfigMap
metadata:
    name: cm-private-api
    namespace: public
data:
    PRIVATE_API: ENC[AES256_GCM,data:H+O6uoSzEgWAEhNucSyRn584yVeZ2arJbStbmWAWQjKbNPxSBqFN/8AnjjlnVbDKNJS2ZKmbMMA92IziHQ==,iv:qhB24lVICezR0XAt6W9xsEQKm9Bgsl1NJ1BC1mzRHRc=,tag:vRfamYRJFPjSEZ24oCMmUA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:367816904393:key/fb611257-edc6-487e-8e6d-62b089ae6ef9
          created_at: "2022-04-13T16:54:17Z"
          enc: AQICAHj9y4jwzVh1ScftfkXqEeOrE1TqkYoOoIbQDmcnTS3ukwEtterJq0koW7wxA+bXh9FuAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMEaAGTvEp1A5DlsIvAgEQgDtZ39hvjJsTOGc8MBmhhVE9w6YBx/sw5UZNGN7OtcAlHaZ/IwGARqylh0V8Qho8z3vF/uLrKpHbKPc5ug==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-13T16:54:18Z"
    mac: ENC[AES256_GCM,data:dT7bmrJPNcq29UtSwFlYk3A+cY2yLk1v8ukAdiU2KAabE/JaMYDIGbYLrC38jGs9PIuLQ30d8Cs+Gm8agsdQPk2+atYMCg6ggDjQ64dKdgmPMNdNclE026YV3vFhVjrCHKeW3QWRyi1aY5p0r2PlRi4Qu5KlAvHXS9cvR71ab1A=,iv:5lhVZYz70DnepqjI56paOJmq+HqWrjzc6BFmzyOuv2A=,tag:UOiyi0DfkTZHcYLvE1biFw==,type:str]
    pgp:
        - created_at: "2022-04-13T16:54:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9M/oS8IfYXHAQ//UR2h/8ybAXepAVieJ8IGfuguogeBqh6MVAqb/FkeS+3L
            MzJHg5c6CXkCSCPLLRD/s6RymhYt2oJ/ZLqdu7PLLNYVnzYLRGqpR/CWd7y+rcQP
            I7lC42pct1ZhmjDVzqc6ZAyzq2fo4yqOCDfsQ1T0m6PRvXY2Ms+bDpXENI1EG5pa
            Rb4IU65KNScI70Z6IdG9Fid6n33Pr7NvUZ3YF3xe6zgey/3qUM4KKuFhbIC30tHx
            Sdt+tBotFXxcjbQUtKqH4Nev7pyBAmJEnEHF4ZICzM1kPQYNF5OdK7dem6Gv56kK
            hrwdEWmgaQA5afcr2sY2Y4ffsY7sv+6qh5HDfZfg25/tshxzegsm1VvtmxpzzxBN
            nLxQM9I+Nsut9kymbrBIDFKfAC8aJImxv+HYcyVNXA+BQ57NEWLL2uEGSzR2qxdu
            GZbEtZMMF55hwRcvX8vYfSU/NZjVdiQuwoYDhPWoPjMgxS7Y6gUEfuYJFVKSDPd7
            SfwTr0NOinSjoARdKonQMeRkI9Fk9hrmO/LW3nbQUndFtB7A21d7TB+hSqtBsZwa
            85zyy25b/bqw2hzuyR1kv9x09sLeyqurdEo7KKiEKd4XROK9jvt4X7EZEC+rYqWo
            1+127vQGS9TwRQHIsqCON39g+rCgmOZja+NFpzluC4VZogaJS92TOWAAbdZY6CfS
            XAERqDdkbAPRDopemvGzjf2Oa8f4IQFls2ZRn5FqxlvB3gnp2TJeroyAsXhP0qb0
            rZuZtKMfwjj80YZCihFSNBOAAg9139PLPa3lYsliGiuj27cQQhKuKEtusEU1
            =vI++
            -----END PGP MESSAGE-----
          fp: C3FEBC7F6AA094882569460B7EEA4945E3CB4D5B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: cm-webpage-config
    namespace: public
data:
    CONFIG_JS: ENC[AES256_GCM,data:bIPlTALoxRM6fXPezzSPLDPYNIVfsKp0uKplWjgec/JpP1mzYzNvxj0X/MZSGDl0tGJa2RqSRxardbEhY+n2VoMLGxDGZrDh3778aAzBD/LEPWYYfF8oTFXdF09ZHejkvYRtly4mpX1A1ynqwtN+KWYZayjv7a6/VfAks1MDL+vrHt1+chg=,iv:FVMmlzegVIqDSN183ejZmMyAf9Wsll5ZXpSN8ERBd9A=,tag:XPcOUD9nYHUQZD/mWfzbKA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:367816904393:key/fb611257-edc6-487e-8e6d-62b089ae6ef9
          created_at: "2022-04-13T16:54:17Z"
          enc: AQICAHj9y4jwzVh1ScftfkXqEeOrE1TqkYoOoIbQDmcnTS3ukwEtterJq0koW7wxA+bXh9FuAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMEaAGTvEp1A5DlsIvAgEQgDtZ39hvjJsTOGc8MBmhhVE9w6YBx/sw5UZNGN7OtcAlHaZ/IwGARqylh0V8Qho8z3vF/uLrKpHbKPc5ug==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-13T16:54:18Z"
    mac: ENC[AES256_GCM,data:dT7bmrJPNcq29UtSwFlYk3A+cY2yLk1v8ukAdiU2KAabE/JaMYDIGbYLrC38jGs9PIuLQ30d8Cs+Gm8agsdQPk2+atYMCg6ggDjQ64dKdgmPMNdNclE026YV3vFhVjrCHKeW3QWRyi1aY5p0r2PlRi4Qu5KlAvHXS9cvR71ab1A=,iv:5lhVZYz70DnepqjI56paOJmq+HqWrjzc6BFmzyOuv2A=,tag:UOiyi0DfkTZHcYLvE1biFw==,type:str]
    pgp:
        - created_at: "2022-04-13T16:54:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9M/oS8IfYXHAQ//UR2h/8ybAXepAVieJ8IGfuguogeBqh6MVAqb/FkeS+3L
            MzJHg5c6CXkCSCPLLRD/s6RymhYt2oJ/ZLqdu7PLLNYVnzYLRGqpR/CWd7y+rcQP
            I7lC42pct1ZhmjDVzqc6ZAyzq2fo4yqOCDfsQ1T0m6PRvXY2Ms+bDpXENI1EG5pa
            Rb4IU65KNScI70Z6IdG9Fid6n33Pr7NvUZ3YF3xe6zgey/3qUM4KKuFhbIC30tHx
            Sdt+tBotFXxcjbQUtKqH4Nev7pyBAmJEnEHF4ZICzM1kPQYNF5OdK7dem6Gv56kK
            hrwdEWmgaQA5afcr2sY2Y4ffsY7sv+6qh5HDfZfg25/tshxzegsm1VvtmxpzzxBN
            nLxQM9I+Nsut9kymbrBIDFKfAC8aJImxv+HYcyVNXA+BQ57NEWLL2uEGSzR2qxdu
            GZbEtZMMF55hwRcvX8vYfSU/NZjVdiQuwoYDhPWoPjMgxS7Y6gUEfuYJFVKSDPd7
            SfwTr0NOinSjoARdKonQMeRkI9Fk9hrmO/LW3nbQUndFtB7A21d7TB+hSqtBsZwa
            85zyy25b/bqw2hzuyR1kv9x09sLeyqurdEo7KKiEKd4XROK9jvt4X7EZEC+rYqWo
            1+127vQGS9TwRQHIsqCON39g+rCgmOZja+NFpzluC4VZogaJS92TOWAAbdZY6CfS
            XAERqDdkbAPRDopemvGzjf2Oa8f4IQFls2ZRn5FqxlvB3gnp2TJeroyAsXhP0qb0
            rZuZtKMfwjj80YZCihFSNBOAAg9139PLPa3lYsliGiuj27cQQhKuKEtusEU1
            =vI++
            -----END PGP MESSAGE-----
          fp: C3FEBC7F6AA094882569460B7EEA4945E3CB4D5B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
