apiVersion: v1
kind: Secret
metadata:
    name: secret-token
    namespace: public
data:
    TOKEN_SECRET: ENC[AES256_GCM,data:xxN74ZANpu8=,iv:km/eAHPBgpS8IXEoXcPUvI0beezf94zXeqGKPCiyIFg=,tag:b+wusq+fgvJFzEHex+87yw==,type:str]
type: Opaque
immutable: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-13T07:27:32Z"
    mac: ENC[AES256_GCM,data:mzV8PO0UnncdKMkXL76pHJ3El3RVpY31cpVa1rdNrBHMA9vfMuKJ2zo0Di99PfGbM+z4Tt7BvduvgqqA9fxbZbe+xncpLo0jqXp37eSPus/Uzby6+I/AYlLbRDfzjoXe+Bzlz0aVw7kDG94Q5g/sMtQ9nFF4t70musxzS+R+QLk=,iv:U58M/RZt8EhKO9dH+UTZeqbmBDzqvZnzjVXJSjwWOJI=,tag:2EPpWK/3VxU6YE3fZoBE5w==,type:str]
    pgp:
        - created_at: "2022-04-13T07:27:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9M/oS8IfYXHARAAo7C1tX6o3TyWdlgBx1dofO+DJPrgijI41DJ8Q837YBVn
            eHO7h6SheXsKf/fT7HvuO4rTZ7Sy8GqXB2x2sF4ct+SIBlkx+kQmTFWZueULUK3J
            Qh0H4fm4IYGorN0OyhNKXubClZSOjD7o1jgKlhG0MO5894gymk1Hxsb2IOl85e1z
            LHQO7NJvummdsR3swS0baHqpojBqeyjtdoPoPuvvdQgpDi7khqcB4nMaoPqdeMPb
            wUeXwIOfMk0VfP0t9zMoY70k3YdC7QsaIUXV2g4gPj6q/1YWwIGTQR34KgoI5PFk
            +KeEfAs7N7GgOpExEdiLOrVhCjbeAA/O6F9ejaZ1jN558i53y12XsPSv+zQ88WPJ
            ySL+ysWWAE8G4mIB6RiYg46IEOqPZ5urbIYKe0UjHH/zy/qnYmm5BcnM5TmR6Q0F
            1f2r9IAaWeyaaX6aGWkWJi0pXw1Ubd1HPF78ttDLw4HPcYlxcTT3KOe8+ORJx+Cd
            9f6uAAIG+lJsneHxyiMK/b/QBVVQ/R3qP7RmIf94NCMCfepZnHCiIqK6X3HboV1n
            LnvbSXyngtFtTyIXbMIaBFej4oJMXld4uTn76snNlBAXm/kq6XudkOQ86AFHWErv
            A5e4S7reYa5TGXP14SWgzFCpqKU7Xg0s/6Z8OG6UVnpgqdL1FVBC2CwTAF2aY8vS
            XgEArYJo4NrgBCfW03h+LkGha7q9EHYMCTDyTwplmGoT9TrJTa3/+lVlryfAW7eg
            lqqkJZIjl1fAK9Q+NxmJkIIMuCY5sYqrsrpMToRPIBlaPwYD0NKI/Qb3/YPeDik=
            =7/cW
            -----END PGP MESSAGE-----
          fp: C3FEBC7F6AA094882569460B7EEA4945E3CB4D5B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
