apiVersion: v1
kind: Secret
metadata:
    name: secret-token
    namespace: public
data:
    TOKEN_SECRET: ENC[AES256_GCM,data:Sk27BDd9uJQ=,iv:6MQn0887Ptfho7++OW8OLO57vCISiYnjHJp3JzvJXsA=,tag:exR1WhU1/qI/dD5zioNwfw==,type:str]
type: Opaque
immutable: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-13T08:04:04Z"
    mac: ENC[AES256_GCM,data:1s7LjNVC9sm16ZLNVSTF3HMWsRoI7g6BK26iicZ1EECkaFxt0vP6lO8L0QKrG1wNOnMU279vj8zHsOIGqaRAhdHSWiWabqrO5JhF2mUr71WgXzxPMJU7FB4HkKETKhawhEd01eY3LdbnhyrNhjeMlZ9sD38yoUNC3AQWKgCy5k8=,iv:nk6Nk7O3jUXqHnNPU8bGGvfaa6/TiP4rqJK9DubkxmI=,tag:Wz2aMmw55J1VmSbxzOPCBQ==,type:str]
    pgp:
        - created_at: "2022-04-13T08:04:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9M/oS8IfYXHARAAsa8+Vl/VUC8MLZ060y4rglWDFKxtqxYtdbiMnPe3vzsp
            hmzSMCWzAZAow5sftyt/wzgtmg3MDRu+mF8t9N3o3145R5XLvcjLeujWx4C7AbNi
            8FuDGupIxu/20qilXTqZtHzkfY1Dz5SwWgr81N2/8kU9jQfy0N4k85zkD+JE4EZn
            KkKnb8liXCaBYArxQJYFV3zS+EKaQuyAEqfTaZpE0ONqOw5EkyBn5cf+kuFVOzXX
            phaAgKS7o7fSOcJNYTkIYjD7X3hzCVupTNJ1bhO6evpGruWR2/Am8wugiAQHL1dE
            PqHzokLRpdbKwHrcqYK1pPpq62DqqxBBA1Z+KyC83+nQU8YwnKG1lI4nvam8DkfX
            BQfwgt4Ml5635j49bUwvajmMIsers5DiQ2XSU41i3lVJfdKppUVKq8htlraZWRWE
            1fwO68Ug8VwzPs+lDByGbSdTdml1yc76vavu9EecDVKoVO37WXsLhYGpTgRr2SIp
            glrAbrZt9bm3bS7mJNOHLzGsXtnJWj4mAz+UyzAXFqHEfBv/RLXkLMeojCs9c8n0
            yVOZZePeysUv3n0WXEnDN1AHV6W2g1rWfTLer2uPNkVL3a2hxwAI+UK4HVPxau+z
            1n2aHqShlGZv3uH5EpfMMZynuIjWFHY2/IsmjtYGN5CWiRnT6zQcsnLfw/orMVrS
            XgEM5Ted0Bv7ki+bJG6OBz+mhn2mWDG3gjJG44Tl0l4psTGNi/6RDsgGkFEcqVGr
            moQtYYuriL1Jqd1xZm17Qk/6VeqtcrAZDaxq+uG4HtyPbiJi4MsScyhr9ai8Gn0=
            =z7lB
            -----END PGP MESSAGE-----
          fp: C3FEBC7F6AA094882569460B7EEA4945E3CB4D5B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
