apiVersion: v1
kind: Secret
metadata:
    name: secret-token
    namespace: public
data:
    TOKEN_SECRET: ENC[AES256_GCM,data:h/bI6vWSXOU=,iv:HnyPZKgPGK+9dZQOafu8ouvfPoLvLxGWMb6syEFf3ys=,tag:82X0CLDwdzi+cvsX29tuaw==,type:str]
type: Opaque
immutable: true
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:367816904393:key/fb611257-edc6-487e-8e6d-62b089ae6ef9
          created_at: "2022-04-13T09:48:06Z"
          enc: AQICAHj9y4jwzVh1ScftfkXqEeOrE1TqkYoOoIbQDmcnTS3ukwGZFXk7jozaFKCiVeS8ioAtAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM4paxaZvuA8U0h5IJAgEQgDtt+eNAraZ6D/duqYVIMHMaE2V8izL1jvyK5UoBkxAsF0aN3xPBRpNuhS7MhBl6Uag4cnedCoygTj3Lsg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-13T09:48:07Z"
    mac: ENC[AES256_GCM,data:oACuxb7DVjwPPHxdCQ7iOM3AFeMFAyb52uf6UPInjlADEB4Sn30GUJYWc2uf4NwBehxLVL9LQAa3dYrmulME/LoRzz5ht7T6Tdqc9fl+OpKGum1DiNjo4E1E+xkI6pP+Ok44Y/J45qLsGP7VinpWqxkDgfwSGrKB/vAPYUdP6yg=,iv:WNI+DvPFAz+wEGCOJ9nUWXJG4VjKbOMBlF5x5hAo3xE=,tag:O+B3X2HZsd+ZMARf7+ZxmA==,type:str]
    pgp:
        - created_at: "2022-04-13T09:48:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9M/oS8IfYXHARAAhBvD6HJqprTKDDlTD5Dnys5uGYXoUZSXHIkr2jFffhrv
            eUs4J/Jwmvuo08ncG7GuRKQHXSy8kR/N7QFtMO1SB4V1qljud6wUdpinM/Ld0gP3
            b7msesmOy0UdzchHuEbryTxPV5QuXlqSOeqzcGqhevqvJ4fB7D1zFhVTBESt2YfZ
            NJqKvVVC5qwoBoTq3nx0Wg/g3jRocpLmf8FrNrRy3DQLrk/i0hKinB22Ze763Tm8
            ml41EY9oj2O4xcHXXKlfW7OMOk0UV3tKx1mEhEiBQvXKLWQAhtsgVxpzhV35EwAv
            /9XEHPlMGfgi+zwHIK1M+DG491kzB79bgiIauBoJNjKrk5lfK4Ii+bmi+Sd5upmc
            iF3VKuEGD7psI+6RMdlcqHt+jaOML3BKOA3nxwfAAcDuMQPrhTJoZc8/B8arkUii
            qXFJqqvM0UP4P28BJvV/BqK8hUsFTwhA4ZeLdZ7b3gm6ggJlkUy2/JTQVNdxxuFq
            wvfORWPNt+U7aMfPjkq+dEgNhZAQY3+ECiVeQZnz9WWrT1C40ahDUuzigYzukLeE
            SU/4ZXMkyvfFbAu0cUZ1Hbf4+Fu0tfcN4uOCuiSJmzLX1WJggqhTaK6m3GS0cQgy
            SM+EZiAxQmhKHuxiGO/D0UfaAYyznSdJ0TmUORP2VVRKCnBVuEIeOHq5Cf3f+ubS
            XgEexCmSOJsc//3ZlueIxszPXPFzXFiJhl8K1jUZOX+sTwPCRXaU+VW3xWz9rzcG
            BcNJ+JqKb1RQa6diLijvtBCULiT7YQAvlzplSsildrNLVdPu5pvCoO/quTIlq1U=
            =VmYz
            -----END PGP MESSAGE-----
          fp: C3FEBC7F6AA094882569460B7EEA4945E3CB4D5B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
