apiVersion: v1
kind: Secret
metadata:
    name: secret-token
    namespace: public
data:
    TOKEN_SECRET: ENC[AES256_GCM,data:Efx8w6mcN2g=,iv:hfF1yuN1LwP7JYXWhV3tRktWIuB7+HaQMSoQQcWAHWM=,tag:S0hXI2oKlBG0dvQvRgBfVA==,type:str]
type: Opaque
immutable: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-13T07:21:02Z"
    mac: ENC[AES256_GCM,data:BAhdo2w4s3NHvKevaxm6MC9HvJ3PDvUhUDS1W2oGdWFobp+cTDksB5KmBaJUTmEnSiBOMmwyBkDgQ2E8Rt0B37Faemh+AvLG7Ae3G14CFXrcrUSEyq26FqY4DrE23qQBoKMPu1HP+4U1WFT9XJSIbivxXZGCSsPGCptXpuJ+w6o=,iv:9cSyxblJy3luEnC/zfvU06zeMdvT7ciU+/+6hx5m/Gg=,tag:EEMntTS9rR/dnvyUszt+CA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
