apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demoapp-prod
commonLabels:
  app: demoapp-prod
  env: prod
resources:
- 00-namespace.yaml
- 01-cm-config.yaml
- 02-secret-token.yaml
# - ../../../../../workloads-base/api/demoapp-prod

# patchesStrategicMerge:
# - deployment.yaml
# - destination-rule.yaml
# - virtual-service.yaml
# configMapGenerator:
# - name: policy-enforcer
#   behavior: replace
#   files:
#     - configs/policy-enforcer-devel.json
