creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - kms:
        - arn: "arn:aws:kms:us-east-1:367816904393:key/fb611257-edc6-487e-8e6d-62b089ae6ef9"
          aws_profile: demo # login aws profile
      - pgp:
        - "F2C855951BE1A4DAEF3486D4712637F87E759594"
