apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: public-staging
commonLabels:
  app: demoapp-staging
  env: staging
resources:
- 00-namespace.yml
- 01-cm-config.yml
- 02-secret-token.yml
# - ../../../../../workloads-base/api/demoapp-staging

# patchesStrategicMerge:
# - deployment.yaml
# - destination-rule.yaml
# - virtual-service.yaml
# configMapGenerator:
# - name: policy-enforcer
#   behavior: replace
#   files:
#     - configs/policy-enforcer-devel.json
