apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-private-api
  namespace: public
data:
  PRIVATE_API: http://svc-private-api.private.svc.cluster.local:3002/private
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-webpage-config
  namespace: public

data:
  CONFIG_JS: |
    var config = (() => {
    return {
      API: "http://api.kube-apps.tk/graphql",
      WEBSOCKET: "ws://websocket.kube-apps.tk/graphql",
    };
    })();
